chore: provide more specific defaults for front-end
rtbhouse-apps/renovate-config-public pull request #1
Opened 2022-09-20 12:55 UTC by maxbarnas

https://rtbhouseproduct.atlassian.net/browse/APPS-3144

2022-09-20 19:43 UTC, oskarwrobel approved these changes
Super 👍 

Jeżeli to bangla, to już w ogóle super :D

2022-09-20 19:43 UTC, oskarwrobel commented on default.json
> +      "groupName": "devDependencies"
Rozumiem, że zrobienie tej grupy + grupa na all z linii 4, sprawi, że powstaną dwie grupy? devDeps i reszta, czyli deps.

2022-09-20 19:48 UTC, jacek-jablonski requested changes

2022-09-20 19:48 UTC, jacek-jablonski commented on default.json
> +      "schedule: [
brakuje zamknięcia "

2022-09-20 19:59 UTC, maxbarnas commented on default.json
> +      "schedule: [
dzięki!

2022-09-21 14:27 UTC, jacek-jablonski approved these changes

2022-09-21 14:42 UTC, merged